[package]
name = "wasm-test"
version = "0.1.0"
authors = ["Mateusz Cegiełka <mateusz@cegla.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
reqwest.path = ".."
wasm-bindgen = "0.2.52"
wasm-bindgen-futures = "0.4.1"
